version: '3'
  
services:
  app:
   build: .
   entrypoint: sh ./.docker/entrypoint.sh
   container_name: app-teste
   ports:
    -3000:3000
   restart: always
   tty: true
   networks:
   - api-mongo
  db:
     image: mongo
     ports:
      - 27017:27017
     restart: always

     enviroment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
     tty: true

     networks:
     api-mongo:


